version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 5050:5050
    volumes:
      - ./:/app/
    command: >
      sh -c "python wsgi.py"